apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h24emuzs1-python 
  janus-idp.io/tekton: h24emuzs1-python
  backstage.io/kubernetes-id: h24emuzs1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h24emuzs1-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  